<?php

declare(strict_types=1);

namespace Fabiang\DoctrineMigrationsLiquibase;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-09-20 at 12:51:46.
 *
 * @coversDefaultClass Fabiang\DoctrineMigrationsLiquibase\ConfigProvider
 */
final class ConfigProviderTest extends TestCase
{

    private ConfigProvider $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ConfigProvider;
    }

    /**
     * @test
     * @covers ::__invoke
     */
    public function invoke()
    {
        $this->assertIsCallable($this->object);
        $this->assertIsArray($this->object->__invoke());
    }

    /**
     * @test
     * @covers ::getDependencies
     */
    public function getDependencies()
    {
        $this->assertIsArray($this->object->getDependencies());
        $this->assertArrayHasKey('aliases', $this->object->getDependencies());
        $this->assertArrayHasKey('factories', $this->object->getDependencies());
    }

}
